apiVersion: v1
kind: Namespace
metadata:
  name: task-manager
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: task-manager
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: task-manager
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: taskdb
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi


# env:
#   - name: MONGO_HOST
#     value: mongo
#   - name: MONGO_PORT
#     value: "27017"
#   - name: MONGO_DB
#     value: taskdb
#   - name: MONGO_USER
#     value: taskuser
#   - name: MONGO_PASSWORD
#     value: taskpass




# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo
#   namespace: task-manager
# spec:
#   ports:
#     - port: 27017
#   selector:
#     app: mongo
